Traceback (most recent call last):
  File "/home/zhang146/stable-baselines3/main.py", line 936, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 740, in make
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/gymnasium/envs/mujoco/humanoid_v5.py", line 370, in __init__
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_env.py", line 78, in __init__
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_env.py", line 128, in _initialize_simulation
ValueError: mjParseXML: could not open file '/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/gymnasium/envs/mujoco/assets/humanoid.xml'
Exception ignored in atexit callback: <function dump_compile_times at 0x1554479f85e0>
Traceback (most recent call last):
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 446, in dump_compile_times
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 432, in compile_times
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 207, in tabulate
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1439, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1548, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1591, in _fill_cache
OSError: [Errno 23] Too many open files in system: '/home/zhang146/stable-baselines3'
Traceback (most recent call last):
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/weakref.py", line 667, in _exitfunc
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/weakref.py", line 591, in __call__
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/tempfile.py", line 859, in _cleanup
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/tempfile.py", line 855, in _rmtree
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/shutil.py", line 721, in rmtree
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/shutil.py", line 718, in rmtree
OSError: [Errno 23] Too many open files in system: '/tmp/tmprvosgfsg'
