Traceback (most recent call last):
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/forkserver.py", line 274, in main
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/forkserver.py", line 313, in _serve_one
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
Traceback (most recent call last):
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/forkserver.py", line 274, in main
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 289, in run_path
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/forkserver.py", line 313, in _serve_one
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 96, in _run_module_code
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 86, in _run_code
  File "/home/zhang146/stable-baselines3/main_trpo.py", line 2, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
  File "/home/zhang146/stable-baselines3/stable_baselines3/__init__.py", line 3, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/home/zhang146/stable-baselines3/stable_baselines3/a2c/__init__.py", line 1, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 289, in run_path
  File "/home/zhang146/stable-baselines3/stable_baselines3/a2c/a2c.py", line 3, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 96, in _run_module_code
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/torch/__init__.py", line 2253, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 86, in _run_code
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/torch/masked/__init__.py", line 1, in <module>
  File "/home/zhang146/stable-baselines3/main_trpo.py", line 2, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/torch/masked/_ops.py", line 10, in <module>
  File "/home/zhang146/stable-baselines3/stable_baselines3/__init__.py", line 3, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/torch/masked/maskedtensor/__init__.py", line 7, in <module>
  File "/home/zhang146/stable-baselines3/stable_baselines3/a2c/__init__.py", line 1, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/torch/masked/maskedtensor/reductions.py", line 9, in <module>
  File "/home/zhang146/stable-baselines3/stable_baselines3/a2c/a2c.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/torch/__init__.py", line 2593, in <module>
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/torch/func/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
OSError: [Errno 23] Too many open files in system: '/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/torch/masked/maskedtensor/creation.py'
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
OSError: [Errno 23] Too many open files in system: '/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/torch/_functorch/eager_transforms.py'
Traceback (most recent call last):
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/forkserver.py", line 274, in main
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/forkserver.py", line 313, in _serve_one
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 289, in run_path
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 96, in _run_module_code
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 86, in _run_code
  File "/home/zhang146/stable-baselines3/main_trpo.py", line 2, in <module>
  File "/home/zhang146/stable-baselines3/stable_baselines3/__init__.py", line 3, in <module>
  File "/home/zhang146/stable-baselines3/stable_baselines3/a2c/__init__.py", line 1, in <module>
  File "/home/zhang146/stable-baselines3/stable_baselines3/a2c/a2c.py", line 3, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/torch/__init__.py", line 2253, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/torch/masked/__init__.py", line 1, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/torch/masked/_ops.py", line 10, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/torch/masked/maskedtensor/__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
OSError: [Errno 23] Too many open files in system: '/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/torch/masked/maskedtensor/unary.py'
Traceback (most recent call last):
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/forkserver.py", line 274, in main
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/forkserver.py", line 313, in _serve_one
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 289, in run_path
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 96, in _run_module_code
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/runpy.py", line 86, in _run_code
  File "/home/zhang146/stable-baselines3/main_trpo.py", line 2, in <module>
  File "/home/zhang146/stable-baselines3/stable_baselines3/__init__.py", line 3, in <module>
  File "/home/zhang146/stable-baselines3/stable_baselines3/a2c/__init__.py", line 1, in <module>
  File "/home/zhang146/stable-baselines3/stable_baselines3/a2c/a2c.py", line 3, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/torch/__init__.py", line 2604, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/torch/_meta_registrations.py", line 11, in <module>
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/torch/_decomp/__init__.py", line 284, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
OSError: [Errno 23] Too many open files in system: '/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/site-packages/torch/_decomp/decompositions.py'
Traceback (most recent call last):
  File "/home/zhang146/stable-baselines3/main_trpo.py", line 910, in <module>
    dummy_env = SubprocVecEnv(dummy_env_fns)
  File "/home/zhang146/stable-baselines3/stable_baselines3/common/vec_env/subproc_vec_env.py", line 119, in __init__
    observation_space, action_space = self.remotes[0].recv()
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/zhang146/anaconda3/envs/continualrl/lib/python3.10/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
